webpack.prod.js: fix a new Node syntax issue
Without this fix, I am getting with Node 22:

```
SyntaxError: Unexpected identifier 'assert'
```

The issue is explained in this answer:
https://stackoverflow.com/a/78876692/598057

```
... Thus, swapping from assert to with will fix your program for Node 22 and later at the expense of breaking it for Node 16 and 17.
```